version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: messenger-server
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=messenger_user
      - DB_PASSWORD=frT@34jk
      - DB_NAME=messenger_db
    ports:
      - "3001:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    command: npm run dev

  db:
    image: postgres:13-alpine
    container_name: messenger-db
    environment:
      - POSTGRES_USER=messenger_user
      - POSTGRES_PASSWORD=frT@34jk
      - POSTGRES_DB=messenger_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
